### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by rst-afzal** [chekalsky/phpcs-action#11]
Hi,

I'm getting the following error , when the workflow executes

`ERROR: You must supply at least one file or directory to process`

Below is my yaml file, Am I missing anything

```
name: PHPCS check

 on: pull_request

 jobs:
   phpcs:
       name: PHPCS
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: PHPCS check
           uses: chekalsky/phpcs-action@v1
```
