### ISSUE TITLE
Option for installed_paths

### ISSUE THREAD

**Issue by bueltge** [chekalsky/phpcs-action#6]
Would be great that we have also the possibility to add options like `installed_paths` so we can set config like `phpcs --config-set installed_paths "../../coding-standards/example/,../../automattic/phpcs-neutron-standard/"`

About this option: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths

maybe like 
```
inputs:
  enable_warnings:
    description: 'Enable checking for warnings (-w)'
    required: false
    default: ''
  installed_paths:
    description: 'Setting the installed standard paths'
    required: false
    default: ''
```
