### ISSUE TITLE
Referenced sniff "Doctrine" does not exist

### ISSUE THREAD

**Issue by stephanvierkant** [chekalsky/phpcs-action#9]
I want to run phpcs with a Doctrine code standard. This is my configuration:

```
//..
jobs:
  phpcs:
      name: chekalsky/phpcs-action@v1
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: composer install --prefer-dist --no-progress --no-suggest --no-scripts
        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
            enable_warnings: true
            phpcs_bin_path: './vendor/bin/phpcs'
```

But it gives my this error:

> ERROR: Referenced sniff "Doctrine" does not exist

My composer.json includes:

```
  "require-dev": {
    "doctrine/coding-standard": "^7.0",
   }
```

That means this is also installed:

> "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
>  "slevomat/coding-standard": "^6.0",
>  "squizlabs/php_codesniffer": "^3.5.3"

I see dependencies (including doctrine/coding-standard) are installed.

Why can't phpcs find Doctrine?
